version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron" # Runs at the start of every hour
      cronjob: "0 * * * *" # Runs at the start of every hour
    target-branch: "b-2.0-update-symmfony"   
    
