<?php

/**
 * This file is part of O3-Shop.
 *
 * O3-Shop is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * O3-Shop is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with O3-Shop.  If not, see <http://www.gnu.org/licenses/>
 *
 * @copyright  Copyright (c) 2022 OXID eSales AG (https://www.oxid-esales.com)
 * @copyright  Copyright (c) 2022 O3-Shop (https://www.o3-shop.com)
 * @license    https://www.gnu.org/licenses/gpl-3.0  GNU General Public License 3 (GPLv3)
 */

/**
 * In this file, the content for help popups is stored:
 *
 * Syntax for identifier: HELP_TABNAME_INPUTNAME, e.g. HELP_SHOP_CONFIG_BIDIRECTCROSS.
 * !!!The INPUTNAME is same as in lang.php for avoiding even more different Identifiers.!!!
 * In some cases, in lang.php GENERAL_ identifiers are used. In this file, always the tab name is used.
 *
 *
 * HTML Tags for markup (same as in online manual):
 * <span class='navipath_or_inputname'>...</span> for names of input fields, selectlists and Buttons, e.g. <span class='navipath_or_inputname'>Active</span>
 * <span class='userinput_or_code'>...</span> for input in input fields (also options in selectlists) and code
 * <span class='filename_filepath_or_italic'>...</span> for filenames, filepaths and other italic stuff
 * <span class='warning_or_important_hint'>...</span> for warning and important things
 * <ul> and <li> for lists
 */

$aLang = [
    'charset' => 'UTF-8',
    'HELP_ALTERNATIVE_IMAGE_SERVER_NOTE' => 'Alternative URL to remote image server can be specified in configuration file config.inc.php by setting <i>sAltImageUrl</i> and <i>sSSLAltImageUrl</i>.<br> Thus all product pictures will be loaded from this alternative server instead of the local one. However, uploaded files will be stored locally. In this case synchronization to external server has to be done manually or with custom scripts.',
    'HELP_ARTICLE_EXTEND_BLFIXEDPRICE' => 'Wished price can be turned off for this product.',
    'HELP_ARTICLE_EXTEND_BPRICE' => 'Enter the RRP here.',
    'HELP_ARTICLE_EXTEND_EXTURL' => 'In <span class="navipath_or_inputname">External URL</span> you can enter a link where further information about the product is available (e. g. on the manufacturer\'s website). In <span class="navipath_or_inputname">Text for external URL</span> you can enter the text which is linked, e .g. <span class="userinput_or_code">Further information on the manufacturer\'s website</span>.',
    'HELP_ARTICLE_EXTEND_FILE' => 'Here you can specify additional files for the article.',
    'HELP_ARTICLE_EXTEND_FILEUPLOAD' => 'Here you can upload additional files for the article.',
    'HELP_ARTICLE_EXTEND_FREESHIPPING' => 'Setting is inherited from Parent product to Variants and applies to the entire product.',
    'HELP_ARTICLE_EXTEND_ISCONFIGURABLE' => 'If the product is customizable, an additional input field is displayed on the products detail page and in the shopping cart. Here customers can enter text for customizing the product.<br><br>A typical example are t-shirts which can be imprinted with custom text. In the input field customers can enter the text to be printed on the t-shirt.',
    'HELP_ARTICLE_EXTEND_ISSEARCH' => 'Specify whether the article should be found in the search.',
    'HELP_ARTICLE_EXTEND_MASS' => 'Enter the dimensions of the article in meters.',
    'HELP_ARTICLE_EXTEND_NONMATERIAL' => 'Setting is inherited from Parent product to Variants and applies to the entire product.',
    'HELP_ARTICLE_EXTEND_QUESTIONEMAIL' => 'At <span class="navipath_or_inputname">Alt. Contact</span> you can enter an e-mail address. If users submit questions on this product, they will be sent to this e-mail address. If no e-mail address is entered, the query will be send to the normal info e-mail address.',
    'HELP_ARTICLE_EXTEND_SHOWCUSTOMAGREEMENT' => 'If this option is activated, users have to confirm terms and conditions in the fourth step of the check-out process for this specific item. Please make sure the general option is activated as well and the product item is intangible or downloadable.',
    'HELP_ARTICLE_EXTEND_SKIPDISCOUNTS' => 'If <span class="navipath_or_inputname">Skip all negative discounts</span> is active, negative allowances will not be calculated for this product. These include discounts and vouchers.',
    'HELP_ARTICLE_EXTEND_TEMPLATE' => 'The detail view of a product can be displayed with a different template. For doing so, enter path and name of the template to be used.',
    'HELP_ARTICLE_EXTEND_TPRICE' => 'In <span class="navipath_or_inputname">RRP</span> you can enter the recommended retail price of the manufacturer. If you enter the RRP it is shown to the users: Above the product price <span class="filename_filepath_or_italic">Reduced from RRP now only</span> is displayed.',
    'HELP_ARTICLE_EXTEND_UNITQUANTITY' => 'With <span class="navipath_or_inputname">Quantity</span> and <span class="navipath_or_inputname">Unit</span> you can set the price per quantity unit. The price per quantity unit is calculated and displayed with the product (e.g. 1.43 EUR per liter). In <span class="navipath_or_inputname">Quantity</span>, enter the amount of the product (e.g. <span class="userinput_or_code">1.5</span>), in <span class="navipath_or_inputname">Unit</span> define the according quantity unit (e.g. <span class="userinput_or_code">liter</span>). You can choose unit type from given values or, by selecting blank unit type "-", enter unit type manually.',
    'HELP_ARTICLE_EXTEND_UPDATEPRICE' => 'Prices can be changed on a defined time. Given fields update standard prices. If you leave price values "0", prices will not be updated.',
    'HELP_ARTICLE_EXTEND_URLDESC' => 'Enter the text to be displayed instead of the URL here.',
    'HELP_ARTICLE_EXTEND_WEIGHT' => 'Enter the weight of the article in kg.',
    'HELP_ARTICLE_FILES_DOWNLOAD_EXPIRATION_TIME' => 'Specify the time in hours, the download link is valid after the first download. For this file you can overwrite the default setting, which was defined in Master Settings -> Core Setting -> Settings -> Downloads for all products.',
    'HELP_ARTICLE_FILES_LINK_EXPIRATION_TIME' => 'Specify the time in hours, the download link is valid after order. For this file you can overwrite the default setting, which was defined in Master Settings -> Core Setting -> Settings -> Downloads for all products.',
    'HELP_ARTICLE_FILES_LINK_EXPIRATION_TIME_UNREGISTERED' => 'Here you can define how many times user can download from the same link, if user ordered without registration. For this file you can overwrite the default setting, which was defined in Master Settings -> Core Setting -> Settings -> Downloads for all products.',
    'HELP_ARTICLE_FILES_MAX_DOWNLOADS_COUNT' => 'Here you can define how many times user can download from the same link after order. For this file you can overwrite the default setting, which was defined in Master Settings -> Core Setting -> Settings -> Downloads for all products.',
    'HELP_ARTICLE_FILES_NEW' => 'Enter the name of a via FTP transferred file or upload a new file here. Note that large files should be uploaded via FTP. File size limitation is valid only when file is uploaded via admin. This limitation depends on the PHP settings of the server and might be edited only there.',
    'HELP_ARTICLE_IS_DOWNLOADABLE' => 'Files of this product can be downloaded.',
    'HELP_ARTICLE_MAIN_ACTIVE' => 'Indicates whether the article is active or not. Inactive articles are never displayed.',
    'HELP_ARTICLE_MAIN_ACTIVFROMTILL' => 'Specify the period during which the article should be active. If you do not enter a period, the article is always active.',
    'HELP_ARTICLE_MAIN_ALDPRICE' => 'With <span class="navipath_or_inputname">Alt. Prices</span> you can set up special prices for certain users (user groups "Price A", "Price B" and "Price C").',
    'HELP_ARTICLE_MAIN_ARTNUM' => 'The article number of the item.',
    'HELP_ARTICLE_MAIN_DISTEAN' => 'The manufacturer’s EAN of the item.',
    'HELP_ARTICLE_MAIN_EAN' => 'Your own EAN for the item.',
    'HELP_ARTICLE_MAIN_HIDDEN' => 'Hidden articles are not shown in lists. However, they are accessible via search and direct URL.',
    'HELP_ARTICLE_MAIN_MANUFACTURERID' => 'The manufacturer of the item.',
    'HELP_ARTICLE_MAIN_MPN' => 'The manufacturer’s part number (MPN) of the item.',
    'HELP_ARTICLE_MAIN_SEARCHKEYS' => 'Search terms under which the item can also be found.',
    'HELP_ARTICLE_MAIN_SHORTDESC' => 'Short description of the item.',
    'HELP_ARTICLE_MAIN_TITLE' => 'Enter a meaningful product name that can be easily found and ranked by search engines.',
    'HELP_ARTICLE_MAIN_VAT' => 'Here you can enter a special VAT for this product. This VAT is used for this product in all later calculations (cart, order, invoice)',
    'HELP_ARTICLE_MAIN_VENDORID' => 'Your supplier for this item.',
    'HELP_ARTICLE_PICTURES_ICON' => 'Icons are the smallest pictures of a product. For example, they are used in the shopping cart.<br>Uploading custom icon will override icon, generated from the first product picture.<br>After uploading, the filename is shown in Icon. If no icon is uploaded yet, --- is displayed.',
    'HELP_ARTICLE_PICTURES_PIC1' => 'Pictures are used in the detail view of a product. You can upload up to 7 pictures per product. After uploading, the filename is shown in the accordant input field. If no picture is uploaded yet, --- is displayed.<br>Pictures with a maximum of 2 MB or 1500 * 1500 pixel resolution can be uploaded. This restriction is to avoid problems with the PHP memory limit. After uploading, the main picture, zoom picture, thumbnail and icon will be generated automatically.',
    'HELP_ARTICLE_PICTURES_THUMB' => 'Thumbnails are small product pictures. For example, they are used in product lists (categories, search results).<br>Uploading custom thumbnail will override the thumbnail generated from the first product picture.<br>After uploading, the filename is shown in Thumbnail. If no thumbnail is uploaded yet, ---- is displayed.',
    'HELP_ARTICLE_PICTURES_ZOOM1' => 'Zoom pictures are extra large pictures which can be opened from the detail view of a product. <br>You can upload zoom pictures in <span class="navipath_or_inputname">Zoom X upload</span>. After uploading, the filename is shown in <span class="navipath_or_inputname">Zoom X</span>. If no zoom picture is uploaded yet, <span class="userinput_or_code">nopic.jpg</span> is displayed.',
    'HELP_ARTICLE_REVIEW_ACTIVE' => 'Indicates whether this review is visible in the shop.',
    'HELP_ARTICLE_REVIEW_TEXT' => 'The review text written by the customer.',
    'HELP_ARTICLE_SEO_ACTCAT' => 'You can define several SEO URLs for products: For certain categories and manufacturer pages. With <span class="navipath_or_inputname">Active Category/Vendor</span> you can select the SEO URL you want to edit.',
    'HELP_ARTICLE_SEO_DESCRIPTION' => 'This description is integrated in the HTML sourcecode of the product page (META description). This text is often displayed in result pages of search engines. A suitable description can be entered here. If it\'s left blank, the description is generated automatically.',
    'HELP_ARTICLE_SEO_FIXED' => 'You can let the Shop recalculate the SEO URLs. A product page gets a new SEO URL if e. g. the title of the product has changed. The setting <span class="navipath_or_inputname">Fixed URL</span> prevents this: If it is active, the old SEO URL is kept and no new SEO URL is calculated.',
    'HELP_ARTICLE_SEO_KEYWORDS' => 'These keywords are integrated in the HTML sourcecode of the product page (META keywords). This information is used by search engines. Suitable keywords for the product can be entered here. If it\'s left blank, the keywords are generated automatically.',
    'HELP_ARTICLE_STOCK_AMOUNTPRICE_AMOUNTFROM' => 'In <span class="navipath_or_inputname">Quantity From/To/bis</span> you can set which quantity range the scale price is valid for.',
    'HELP_ARTICLE_STOCK_AMOUNTPRICE_PRICE' => 'Here you can set the price for the quantity entered above. You can enter the price absolutely or as percental discount.<br> Further information about scale prices can be found in the <a href="http://www.oxid-esales.com/en/resources/help-faq/eshop-manual/setting-graduated-prices" target="_blank">scale price article in the manual.</a>.',
    'HELP_ARTICLE_STOCK_DELIVERY' => 'Here you can enter the date when the product will be available again if it is sold out. The format is year-month-day, e. g. 2009-02-16.',
    'HELP_ARTICLE_STOCK_DELTIME' => 'The delivery time of the item. Please enter both values.',
    'HELP_ARTICLE_STOCK_NOSTOCKTEXT' => 'Here you can enter a message which is shown if the product is out of stock.',
    'HELP_ARTICLE_STOCK_REMINDACTIV' => 'Setting is inherited from Parent product to Variants and applies to the entire product.',
    'HELP_ARTICLE_STOCK_REMINDAMAOUNT' => 'With <span class="navipath_or_inputname">Send e-mail if stock falls below value</span> you can specify that an e-mail will be sent as soon as the stock level falls below the value entered. Select the check box and then enter the level at which you want to be notified.',
    'HELP_ARTICLE_STOCK_STOCK' => 'The current stock level of the item. This is updated automatically when the item is purchased.',
    'HELP_ARTICLE_STOCK_STOCKFLAG' => 'At <span class="navipath_or_inputname">Delivery status</span> you can select from 4 settings:<ul><li><span class="userinput_or_code">Standard</span>: The product can then also be ordered if it is sold out.</li><li><span class="userinput_or_code">External storehouse</span>: The product can always be purchased and is always displayed as <span class="filename_filepath_or_italic">in stock</span>. (The stock level cannot be given for external storehouse. Therefore, the product is always shown as <span class="filename_filepath_or_italic">in stock</span>).</li><li><span class="userinput_or_code">If out of stock, offline</span>: The product is not displayed if it is sold out.</li><li><span class="userinput_or_code">If out of stock, not orderable</span>: The product is displayed if it is sold out but it cannot be ordered.</li></ul>',
    'HELP_ARTICLE_STOCK_STOCKTEXT' => 'Here you can enter a message which is shown if the product is in stock.',
    'HELP_ARTICLE_VARIANT_SELECTLIST' => 'The selection lists assigned to this article variant.',
    'HELP_ARTICLE_VARIANT_VARNAME' => '<span class="navipath_or_inputname">Name of Selection</span> defines how the selection of the variants is labeled , e.g. <span class="userinput_or_code">Color</span> or <span class="userinput_or_code">Size</span>.',
    'HELP_ATTRIBUTE_MAIN_DISPLAYINBASKET' => 'If checked, this attribute\'s value will be shown in cart and order overview below the product title.',
    'HELP_ATTRIBUTE_MAIN_SORTING' => 'Sorting. This allows you to display various attributes in the desired order.',
    'HELP_CATEGORY_MAIN_ACTIVE' => 'Is the category active? Only active categories are displayed in the category navigation.',
    'HELP_CATEGORY_MAIN_DEFSORT' => 'With <span class="navipath_or_inputname">Fast Sorting</span> you specify the manner in which the products in the category will be sorted.',
    'HELP_CATEGORY_MAIN_DESCRIPTION' => 'The category short description.',
    'HELP_CATEGORY_MAIN_EXTLINK' => 'With <span class="navipath_or_inputname">External Link</span>, you can enter a link that opens when users click on the category. <span class="warning_or_important_hint">Use this function only if you want to display a link in the category navigation. It causes the category to lose its normal function!</span>',
    'HELP_CATEGORY_MAIN_HIDDEN' => 'With <span class="navipath_or_inputname">Hidden</span> <ou can define if this category is shown to users. If a category is hidden it is not shown to the users, even if it is active.',
    'HELP_CATEGORY_MAIN_ICON' => 'Icon for the category.',
    'HELP_CATEGORY_MAIN_PARENTID' => 'In <span class="navipath_or_inputname">Subcategory Of</span> you specify the point at which the category is to appear:<br><ul><li>If the category is not to be a subcategory of any other category, then select <span class="userinput_or_code">--</span> Off.</li><li>If the category is to be a subcategory of another category, then select the appropriate category.</li></ul>',
    'HELP_CATEGORY_MAIN_PRICEFROMTILL' => 'With <span class="navipath_or_inputname">Price From/To</span> you can specify that <span class="warning_or_important_hint">all</span> products in a certain price range are shown in this category. Enter the lower limit in the first entry field and the upper limit in the second entry field. Then <span class="warning_or_important_hint">all products of the Shop</span> within this price range are shown in this category.',
    'HELP_CATEGORY_MAIN_PROMOTION_ICON' => 'With <span class="navipath_or_inputname">promotion icon</span> and <span class="navipath_or_inputname">upload icon</span> you can upload a category picture for promotion on start page. For displaying category promotion see <span class="navipath_or_inputname">Master Settings -> Customer Info -> Top offer in categories</span>',
    'HELP_CATEGORY_MAIN_SKIPDISCOUNTS' => '<li>If <span class="navipath_or_inputname">Skip all negative discounts</span> is active, negative allowances will not be calculated for any products in this category.',
    'HELP_CATEGORY_MAIN_SORT' => 'You can use <span class="navipath_or_inputname">Sorting</span> to define the order in which categories are displayed: The category with the lowest number is displayed at the top, and the category with the highest number at the bottom.',
    'HELP_CATEGORY_MAIN_TEMPLATE' => 'A separate template for the category, if desired.',
    'HELP_CATEGORY_MAIN_THUMB' => 'With <span class="navipath_or_inputname">Picture</span> and <span class="navipath_or_inputname">Upload Picture</span> you can upload a picture for this category. The picture is shown at top of the category is viewed. Select the picture in <span class="navipath_or_inputname">Upload Picture</span>. When clicking on <span class="navipath_or_inputname">Save</span>, the picture is uploaded. After uploading, the filename of the picture is shown in <span class="navipath_or_inputname">Picture</span>.',
    'HELP_CATEGORY_MAIN_TITLE' => 'The name of the category. Displayed in the category navigation.',
    'HELP_CATEGORY_MAIN_VAT' => 'Is there a special VAT for the items in this category?',
    'HELP_CATEGORY_SEO_DESCRIPTION' => 'This description is integrated in the HTML sourcecode of the category page (META description). This text is often displayed in result pages of search engines. A suitable description can be entered here. If it\'s left blank, the description is generated automatically.',
    'HELP_CATEGORY_SEO_FIXED' => 'You can let the Shop recalculate the SEO URLs. A category page gets a new SEO URL if e. g. the title of the category has changed. The setting <span class="navipath_or_inputname">Fixed URL</span> prevents this: If it is active, the old SEO URL is kept and no new SEO URL is calculated.',
    'HELP_CATEGORY_SEO_KEYWORDS' => 'These keywords are integrated in the HTML sourcecode of the category page (META keywords). This information is used by search engines. Suitable keywords for the category can be entered here. If it\'s left blank, the keywords are generated automatically.',
    'HELP_CATEGORY_SEO_SHOWSUFFIX' => 'With this setting you can specify if the title suffix is shown in the browser window title when the category page is opened. The title suffix can be set in <span class="navipath_or_inputname">Master Settings -> Core Settings -> SEO -> Title Suffix</span>.',
    'HELP_CONTENT_MAIN_CATEGORY' => 'If you select <span class="navipath_or_inputname">Category</span>, a link to this CMS page is shown in the category navigation below the other categories.',
    'HELP_CONTENT_MAIN_INSERTBEFORE' => 'Select the content item before which this content will be inserted in the shop.',
    'HELP_CONTENT_MAIN_ISPLAIN' => 'Define CMS entries as plain if they are not allowed to contain HTML formatted content. For example, for text-only emails. This means that no editor is shown, for example.',
    'HELP_CONTENT_MAIN_MAINMENU' => 'If you select <span class="navipath_or_inputname">Upper Menu</span>, a link to this CMS page is shown in the upper menu (At Terms and About Us).',
    'HELP_CONTENT_MAIN_MANUAL' => 'If you select <span class="navipath_or_inputname">Manually</span>, a link is created which you can use to include this CMS page in other CMS pages. The link is shown below when you click on <span class="navipath_or_inputname">Save</span>',
    'HELP_CONTENT_MAIN_SNIPPET' => 'If you select <span class="navipath_or_inputname">Snippet</span> you can include this CMS page within other CMS pages by its ident: <span class="userinput_or_code">[{ oxcontent ident=ident_of_the_cms_page }]</span>',
    'HELP_CONTENT_SEO_DESCRIPTION' => 'This description is integrated in the HTML sourcecode of the CMS page (META description). This text is often displayed in result pages of search engines. A suitable description can be entered here. If it\'s left blank, the description is generated automatically.',
    'HELP_CONTENT_SEO_FIXED' => 'You can let the Shop recalculate the SEO URLs. A CMS page gets a new SEO URL if e. g. the title of the CMS page has changed. The setting <span class="navipath_or_inputname">Fixed URL</span> prevents this: If it is active, the old SEO URL is kept and no new SEO URL is calculated.',
    'HELP_CONTENT_SEO_KEYWORDS' => 'These keywords are integrated in the HTML sourcecode of the CMS page (META keywords). This information is used by search engines. Suitable keywords for the CMS page can be entered here. If it\'s left blank, the keywords are generated automatically.',
    'HELP_COUNTRY_MAIN_ISO2' => 'ISO2, for example "DE".',
    'HELP_COUNTRY_MAIN_ISO3' => 'ISO3, for example "DEU".',
    'HELP_COUNTRY_MAIN_ISOUNNUM' => 'ISO-UN number of the country.',
    'HELP_COUNTRY_MAIN_OXVATSTATUS_0' => 'No VAT is charged for this country under any circumstances.',
    'HELP_COUNTRY_MAIN_OXVATSTATUS_1' => 'VAT is not charged only if a valid VAT ID has been provided.',
    'HELP_DELIVERYSET_MAIN_POS' => '<span class="navipath_or_inputname">Sorting</span> specifies the order in which the shipping methods are displayed to users: The shipping method with the lowest number is displayed at the top.',
    'HELP_DELIVERY_MAIN_CONDITION' => 'In <span class="navipath_or_inputname">Condition</span> you can specify that the shipping cost rule applies only to a certain condition. You can choose from among 4 conditions:<ul><li><span class="userinput_or_code">Amount</span>: Number of products in the shopping cart.</li><li><span class="userinput_or_code">Size</span>: Total size of all products. In order for this setting to be used properly, the size must be entered for products.</li><li><span class="userinput_or_code">Weight</span>: Total weight of the order in kilograms. In order for this setting to be used properly, the weight must be entered for products.</li><li><span class="userinput_or_code">Price</span>: Purchase price of the order.</li></ul>You can use the entry fields <span class="navipath_or_inputname">>=</span> (greater than or equal to) and <span class="navipath_or_inputname"><=</span> (less than or equal to) to specify the range to which the condition is to apply. A larger number must be entered for <span class="navipath_or_inputname"><=</span> than for <span class="navipath_or_inputname">-></span>.',
    'HELP_DELIVERY_MAIN_COUNTRULES' => 'Under <span class="navipath_or_inputname">Calculation Rules</span> you can select how often the price is calculated:<ul><li><span class="userinput_or_code">Once per cart</span>: Price is calculated once for the entire order.</li><li><span class="userinput_or_code">Once for each different product</span>: Price is calculated once for each different product in the shopping cart. It makes no difference what quantity of a product is ordered.</li><li><span class="userinput_or_code">For each product</span>: price is calculated for each product in the shopping cart.</li></ul>',
    'HELP_DELIVERY_MAIN_FINALIZE' => 'You can use <span class="navipath_or_inputname">Don\'t calculate further rules if this rule matches</span> to specify that no further rules are to be run if this shipping cost rule is valid and is being run. For this option, the order in which the shipping cost rules are run is important. It is specified through the <span class="navipath_or_inputname">Order of Rule processing</span>.',
    'HELP_DELIVERY_MAIN_ORDER' => 'You can use <span class="navipath_or_inputname">Order of rule processing</span> to specify the order in which the shipping cost rules will be run. The shipping cost rule with the lowest number is run first. The order is important if the setting <span class="navipath_or_inputname">Don\'t calculate further rules if this rule matches</span> is used.',
    'HELP_DELIVERY_MAIN_PRICE' => 'You can use <span class="navipath_or_inputname">Price Surcharge/Discount</span> to specify the magnitude of the shipping costs. The price can be calculated in two different ways:<ul><li>With <span class="userinput_or_code">abs</span>, the price is specified absolutely (e.g.: with <span class="userinput_or_code">6.90</span>, a price of EUR 6.90 is calculated).</li><li>With <span class="userinput_or_code">%</span>, the price is specified relative to the purchase price (e.g.: With <span class="userinput_or_code">10</span>, a price of 10% of the purchase price is calculated).</li></ul>',
    'HELP_DISCOUNT_MAIN_AMOUNT' => 'You can use <span class="navipath_or_inputname">Quantity</span> to specify that the discount is only valid for certain purchase quantities. If you want the discount to be valid for all purchase quantities, enter <span class="userinput_or_code">0</span> in <span class="navipath_or_inputname">From</span> and <span class="userinput_or_code">0</span> in <span class="navipath_or_inputname">To</span>.',
    'HELP_DISCOUNT_MAIN_EXTRA' => 'Specify a free bonus product that is automatically added to the cart when the discount conditions are met.',
    'HELP_DISCOUNT_MAIN_PRICE' => 'You can use <span class="navipath_or_inputname">Purchase Price</span> to specify that the discount is only valid for certain purchase prices. If the discount is to be valid for all purchase prices, enter <span class="userinput_or_code">0</span> in <span class="navipath_or_inputname">From</span> and <span class="userinput_or_code">0</span> in <span class="navipath_or_inputname">To</span>.',
    'HELP_DISCOUNT_MAIN_REBATE' => 'In <span class="navipath_or_inputname">Discount</span>, you specify the magnitude of the discount. You can use the selection list after the entry field to specify whether the discount is to be applied as an absolute discount or as a percentage discount:<ul><li><span class="userinput_or_code">abs</span>: The discount is an absolute discount, e.g. EUR 5.</li><li><span class="userinput_or_code">%</span>: The discount is a percentage discount, e.g. 10 percent of the purchase price.</li><li><span class="userinput_or_code">itm</span>: Discount in the form of a free product. Set the amount of this product. Choose "Multiply" if the amount of discounted product in shopping cart should be multiplied with the amount of the free product.</li></ul>',
    'HELP_DISCOUNT_MAIN_SORT' => 'Use <span class="navipath_or_inputname">Sorting</span> to define the order of the discounts applied to products or cart. The discount with the lowest number applies first, the one with the highest number last.',
    'HELP_DYNBASE_ADDCATTOCAMPAIGN' => 'Enable this option to include the main category of articles as a campaign parameter in tracking URLs.',
    'HELP_GENERAL_ACTIVE' => 'Indicates whether the shop is active or not. Inactive shops are not displayed.',
    'HELP_GENERAL_ACTIVFROMTILL' => 'Specify the period during which this should be active. If you do not enter a period, this is always active.',
    'HELP_GENERAL_BEGINDATE' => 'The start date. Day, month, year, and time.',
    'HELP_GENERAL_BILLSAL' => 'The salutation.',
    'HELP_GENERAL_BIRTHDATE' => 'The date of birth. Day, month, and year.',
    'HELP_GENERAL_CATEGORYSELECT' => 'The category this entry is assigned to.',
    'HELP_GENERAL_COMPANY' => 'The company.',
    'HELP_GENERAL_COUNTRY' => 'The country.',
    'HELP_GENERAL_DATE' => 'The date of this entry.',
    'HELP_GENERAL_DELIVERYCOST' => 'The applicable shipping costs.',
    'HELP_GENERAL_DESCRIPTION' => 'The description.',
    'HELP_GENERAL_EMAIL' => 'The email address.',
    'HELP_GENERAL_ENDDATE' => 'The end date. Day, month, year, and time.',
    'HELP_GENERAL_EXPORTCAMPAIGN' => 'The campaign parameter appended to the exported URLs.',
    'HELP_GENERAL_EXPORTCUSTOMHEADER' => 'A user-defined header line for the export file.',
    'HELP_GENERAL_EXPORTDELCOST' => 'The shipping costs to be used during export.',
    'HELP_GENERAL_EXPORTLANGUAGE' => 'The language for which the export is generated.',
    'HELP_GENERAL_EXPORTMAINVARS' => 'Indicates whether the base product of variants is included in the export.',
    'HELP_GENERAL_EXPORTMINPRICE' => 'Only articles at or above this minimum gross price are exported.',
    'HELP_GENERAL_EXPORTMINSTOCK' => 'Only articles with at least this stock quantity are exported.',
    'HELP_GENERAL_EXPOSTVARS' => 'Indicates whether variants are included in the export.',
    'HELP_GENERAL_EXTRAINFO' => 'Useful additional information.',
    'HELP_GENERAL_FAX' => 'The fax number.',
    'HELP_GENERAL_FIELDS' => 'Fields that are additionally requested from customers. For example: IBAN, bank, BIC for direct debit.',
    'HELP_GENERAL_FON' => 'The phone number.',
    'HELP_GENERAL_ICON' => 'An icon/logo for the manufacturer.',
    'HELP_GENERAL_IDENT' => 'The unique identifier of this entry.',
    'HELP_GENERAL_INFOLDER' => 'The folder this entry is assigned to.',
    'HELP_GENERAL_LANGUAGE' => 'Language for displaying the information.',
    'HELP_GENERAL_LINK' => 'The link associated with this entry.',
    'HELP_GENERAL_NAME' => 'First and last name.',
    'HELP_GENERAL_ORDERNUM' => 'The sort order number of this entry.',
    'HELP_GENERAL_PRICE' => 'The price of this article.',
    'HELP_GENERAL_SEARCHKEY' => 'Optional search keywords by which this entry can be found.',
    'HELP_GENERAL_SEO_ACTCAT' => 'You can define several SEO URLs for products: For certain categories and manufacturer pages. With <span class="navipath_or_inputname">Active Category/Vendor</span> you can select the SEO URL you want to edit.',
    'HELP_GENERAL_SEO_FIXED' => 'The Shop automatically recalculate the SEO URLs. For example, a product page gets a new SEO URL if the title of the product has changed. The setting <span class="navipath_or_inputname">Fixed URL</span> prevents the recalculation: If it is active, the old SEO URL is kept and no new SEO URL is generated.',
    'HELP_GENERAL_SEO_OXDESCRIPTION' => 'This description is integrated in the HTML sourcecode (META description). This text is often displayed in result pages of search engines. A suitable description can be entered here. If it\'s left blank, the description is generated automatically.',
    'HELP_GENERAL_SEO_OXKEYWORDS' => 'These keywords are integrated in the HTML sourcecode (META keywords). This information is used by search engines. Suitable keywords for the product can be entered here. If it\'s left blank, the keywords are generated automatically.',
    'HELP_GENERAL_SEO_SHOWSUFFIX' => 'With this setting you can specify if the title suffix is shown in the browser window title when the according page is opened. The title suffix can be set in <span class="navipath_or_inputname">Master Settings -> Core Settings -> SEO -> Title Suffix</span>.',
    'HELP_GENERAL_SEO_URL' => 'A URL that is easy to find and rank in search engines.',
    'HELP_GENERAL_SHORTDESC' => 'The short description.',
    'HELP_GENERAL_SORT' => 'Sorting. Higher numbers are sorted further down.',
    'HELP_GENERAL_STATE' => 'The state or province of the address.',
    'HELP_GENERAL_STREET' => 'The street with house number.',
    'HELP_GENERAL_STREETNUM' => 'The house number.',
    'HELP_GENERAL_SUM' => 'The sum.',
    'HELP_GENERAL_TELEPHONE' => 'The phone number.',
    'HELP_GENERAL_TITLE' => 'The designation.',
    'HELP_GENERAL_TYPE' => 'The type of this entry.',
    'HELP_GENERAL_URL' => 'The URL.',
    'HELP_GENERAL_USTID' => 'European VAT identification number.',
    'HELP_GENERAL_ZIPCITY' => 'The postal code.',
    'HELP_GENIMPORT_CSVFILE' => 'Select the CSV file to be imported.',
    'HELP_GENIMPORT_DBFIELDS' => 'Map the columns of the CSV file to the corresponding database fields of the target table.',
    'HELP_GENIMPORT_FIRSTCOLHEADER' => 'Activate this setting if the first line of the CSV file contains the names of the database columns the CSV values are to be assigned to. The values are automatically assigned to the database columns.',
    'HELP_GENIMPORT_REPEATIMPORT' => 'If this setting is active, step one is shown after successful import so you can start the next import immediately.',
    'HELP_GENIMPORT_TABLE' => 'Select the database table into which the imported data will be written.',
    'HELP_LANGUAGE_ABBERVATION' => 'Enter the language abbreviation (e.g. "de" or "en") for this language.',
    'HELP_LANGUAGE_ACTIVE' => 'This option defines language availability in Shops frontend: if it is activated - language is available in frontend. For working in admin area this language is always available; even if it is disabled for frontend.',
    'HELP_LANGUAGE_BASESSLURL' => 'Enter the base SSL URL (https://…) used for this language in the shop.',
    'HELP_LANGUAGE_BASEURL' => 'Enter the base URL (http://…) used for this language in the shop.',
    'HELP_LANGUAGE_DEFAULT' => 'Default language is used when shop is unable to detect language in other ways: language id is not defined by URL, can\'t be detected by browser, is not defined in session etc. Default language can only be disabled, deleting it is <u>not possible</u>.',
    'HELP_LANGUAGE_DESCRIPTION' => 'Enter the full name of the language (e.g. "Deutsch" or "English").',
    'HELP_MANUFACTURER_MAIN_ICON' => 'With <span class="navipath_or_inputname">Icon</span> and <span class="navipath_or_inputname">Upload Icon</span> you can upload a picture for this manufacturer (e. g. the logo).In <span class="navipath_or_inputname">Upload Icon</span>, select the Picture you want to upload. When clicking on <span class="navipath_or_inputname">Save</span> the picture is uploaded. After uploading, the filename is shown in <span class="navipath_or_inputname">Icon</span>.',
    'HELP_MANUFACTURER_MAIN_ICONUPLOAD' => 'Upload an icon/logo for the manufacturer.',
    'HELP_MANUFACTURER_SEO_DESCRIPTION' => 'This description is integrated in the HTML sourcecode of the manufacturer page (META description). This text is often displayed in result pages of search engines. A suitable description can be entered here. If left blank, the description is generated automatically.',
    'HELP_MANUFACTURER_SEO_FIXED' => 'You can let the Shop recalculate the SEO URLs. A manufacturer page gets a new SEO URL if e. g. the title of the manufacturer has changed. The setting <span class="navipath_or_inputname">Fixed URL</span> prevents this: If it is active, the old SEO URL is kept and no new SEO URL is calculated.',
    'HELP_MANUFACTURER_SEO_KEYWORDS' => 'These keywords are integrated in the HTML sourcecode of the manufacturer page (META keywords). This information is used by search engines. Suitable keywords for the manufacturer can be entered here. If left blank, the keywords are generated automatically.',
    'HELP_MANUFACTURER_SEO_SHOWSUFFIX' => 'With this setting you can specify if the title suffix is shown in the browser window title when the manufacturer page is opened. The title suffix can be set in <span class="navipath_or_inputname">Master Settings -> Core Settings -> SEO -> Title Suffix</span>.',
    'HELP_NEWSLETTER_PLAIN_TEXT' => 'Enter the plain-text version of the newsletter here for e-mail clients that do not support HTML.',
    'HELP_NEWS_MAIN_SHORTDESC' => 'Enter a short title text for this news item that will be displayed in the overview.',
    'HELP_ORDER_MAIN_BILLNUM' => 'The invoice number of this order.',
    'HELP_ORDER_MAIN_DELTYPE' => 'The shipping provider used to dispatch this order.',
    'HELP_ORDER_MAIN_DISCOUNT' => 'The discount applied to this order.',
    'HELP_ORDER_MAIN_PAIDON' => 'The date on which payment for this order was received.',
    'HELP_ORDER_MAIN_PAIDWITH' => 'The payment method used to pay for this order.',
    'HELP_ORDER_MAIN_TRACKCODE' => 'The tracking code for shipment tracking of this order.',
    'HELP_ORDER_OVERVIEW_INFOLDER' => 'The folder this order is assigned to.',
    'HELP_PAYMENT_MAIN_ADDPRICE' => 'In <span class="navipath_or_inputname">Price Surcharge/Reduction</span>, the price is entered for the payment method. The price can be specified in two different ways:<ul><li>With <span class="userinput_or_code">abs</span> the price is entered for the payment method (e.g.: if you enter <span class="userinput_or_code">7.50</span> a price of EUR 7.50 is calculated.)</li><li>With <span class="userinput_or_code">%</span>, the price is calculated relative to the purchase price (e.g.: if you enter <span class="userinput_or_code">2</span>, the price is 2 percent of the purchase price)</li></ul>',
    'HELP_PAYMENT_MAIN_ADDSUMRULES' => 'When calculating price surcharge or reduction, cart value is being used as base. Define what costs will be included when calculating cart value.',
    'HELP_PAYMENT_MAIN_AMOUNT' => 'You can use <span class="navipath_or_inputname">Purchase Price</span> to specify that the payment method is only valid for certain purchase prices. The <span class="navipath_or_inputname">from</span> and <span class="navipath_or_inputname">to</span> fields allow you to set a range.<br>If the payment method is to be valid for any purchase price, you must specify a condition that is always met: Enter <span class="userinput_or_code">0</span> in the <span class="navipath_or_inputname">from</span>  and <span class="userinput_or_code">99999999</span> in the <span class="navipath_or_inputname">to</span> field.',
    'HELP_PAYMENT_MAIN_FROMBONI' => 'You can use <span class="navipath_or_inputname">Min. Credit Rating</span> to specify that payment methods are only available to users who have a certain credit index or higher. You can enter the credit rating for each user in <span class="navipath_or_inputname">Administer Users -> Users -> Extended</span>.',
    'HELP_PAYMENT_MAIN_NAME' => 'The name of the payment method.',
    'HELP_PAYMENT_MAIN_SELECTED' => 'You can use <span class="navipath_or_inputname">Selected</span> to define which payment method is be selected as the default method if the user can choose between several payment methods.',
    'HELP_PAYMENT_MAIN_SORT' => 'In <span class="navipath_or_inputname">Sorting</span> you can specify the order in which the payment methods are to be displayed to users: The payment method with the lowest sort number is displayed on top.',
    'HELP_PROMOTIONS_BANNER_PICTUREANDLINK' => 'Upload banner image and enter banner URL which will be used when clicking on banner. If product is assigned to banner and URL is not entered, link to assigned product will be used when clicking on banner.',
    'HELP_REVERSE_PROXY_GET_BACKEND' => 'Admin area is displayed without Reverse Proxy. Varnish header could not be received.',
    'HELP_REVERSE_PROXY_GET_FRONTEND' => 'Checks if Reverse Proxy is available for the frontend. Header of the shop\'s start page is verified.<br>The test could fail if different domains or protocols (http/https) are used for the admin panel and the store front.',
    'HELP_RIGHTSROLES_ACTIVE' => 'Indicates whether the role is active.',
    'HELP_SELECTLIST_MAIN_ADDFIELD_NAME' => 'Enter the name of the new selection list field.',
    'HELP_SELECTLIST_MAIN_ADDFIELD_POS' => 'Enter the sort order (position) of this field within the selection list.',
    'HELP_SELECTLIST_MAIN_ADDFIELD_PREIS' => 'Enter the price surcharge or discount applied to the article price when this field is selected.',
    'HELP_SELECTLIST_MAIN_FIELDS' => 'All available options are displayed in the <span class="navipath_or_inputname">Fields</span> list. You can use the entry fields to the right to set up new options.',
    'HELP_SELECTLIST_MAIN_TITLEIDENT' => 'In <span class="navipath_or_inputname">Working Title</span>, you can enter an additional name that is not displayed to users of your Shop. You can use the working title to differentiate between similar selection lists (e.g., Sizes for trousers and Sizes for shirts).',
    'HELP_SHOP_CACHE_CLASSES' => 'Here you set which view classes are cached.<br> Only change this setting if you are familiar with the caching mechanisms!',
    'HELP_SHOP_CACHE_ENABLED' => 'If Dynamic content caching is active, additional contents are cached for increasing performance. Deactivate this setting as long as you adapt the Shop (writing modules, adapting templates and so on).',
    'HELP_SHOP_CACHE_LAYOUT_CACHE_AGE' => 'Sets lifetime of page layout in seconds. This will be send via HTTP headers, specifying header value "Age".',
    'HELP_SHOP_CACHE_LIFETIME' => 'Here you set how many seconds cached contents are saved at most before they are recreated. The default setting is 36000 seconds.',
    'HELP_SHOP_CACHE_REVERSE_PROXY_ENABLED' => 'Activates a caching HTTP Reverse Proxy. Note: Do not use "Dynamic Content Caching" at the same time, as it could slow down the performance.',
    'HELP_SHOP_CONFIG_ACTIVECATEGORYBYSTART' => 'Defines which category is expanded in the navigation when the shop is opened.',
    'HELP_SHOP_CONFIG_ADDITIONAL_SERVICE_VAT_CALCULATION_BIGGEST_NET' => 'The VAT rate of the products, which have the biggest net value in shopping cart, is used for calculating.',
    'HELP_SHOP_CONFIG_ADDITIONAL_SERVICE_VAT_CALCULATION_PROPORTIONAL' => 'The percentage of products in cart with the same VAT rate is used for calculating.',
    'HELP_SHOP_CONFIG_ALLOWUNEVENAMOUNTS' => 'Allows customers to enter fractional quantities (e.g. 1.5) when ordering.',
    'HELP_SHOP_CONFIG_ALLOW_SUGGEST_ARTICLE' => 'Activate recommendation of products on product detail pages.',
    'HELP_SHOP_CONFIG_ALTVATIDCHECKINTERFACEWSDL' => 'Here you can enter an alternative URL for the online VAT ID check.',
    'HELP_SHOP_CONFIG_AUTOICONS' => 'Automatically generates article icons from thumbnails when no dedicated icon is stored.',
    'HELP_SHOP_CONFIG_BASKETEXCLUDE' => 'Allows to insert products only from one (root) category, if category change is detected user is asked to finalize order (go to checkout) or continue shopping (cart is cleaned in this case). Using this feature in conjunction with  properly organized category structure you can implement split carts for different suppliers.',
    'HELP_SHOP_CONFIG_BASKETRESERVATION' => 'When disabling this option Shop reduces product stock exactly at timewhen order is confirmed by customer and checkout is finished.<br><br> With this option enabled this functionality changes: Product stock reduces and is being <b>reserved</b> when product is put into cart. Reservation is canceled when cart content is bought or cart expires.',
    'HELP_SHOP_CONFIG_BASKETRESERVATIONTIMEOUT' => 'After this timeout the reserved products are returned to stock and customer\'s cart is cleared.',
    'HELP_SHOP_CONFIG_BIDIRECTCROSS' => 'With crossselling you can offer fitting products for a product: If e.g. to a car tires are assigned as crossselling product, the tires are shown with the car.<br>If bidirectional crossselling is activated, it works in both directions: The car is shown with the tires, too.',
    'HELP_SHOP_CONFIG_CALCDELVATONTOP' => 'Shipping costs are entered as net prices and VAT is added on top during calculation.',
    'HELP_SHOP_CONFIG_CALCPAYVATONTOP' => 'Payment method charges are entered as net prices and VAT is added on top.',
    'HELP_SHOP_CONFIG_CALCULATEVATFORDELIVERY' => 'Shipping costs are displayed as net amount plus VAT instead of a gross amount in the cart and on invoices.',
    'HELP_SHOP_CONFIG_CALCULATEVATFORWRAPPING' => 'The VAT contained in gift wrapping and greeting card costs is shown separately in the cart and on invoices.',
    'HELP_SHOP_CONFIG_CALCULATEVATOFORPAYCHARGE' => 'The VAT contained in payment method charges is shown separately in the cart and on invoices.',
    'HELP_SHOP_CONFIG_CALCWRAPVATONTOP' => 'Gift wrapping and greeting card prices are entered as net prices and VAT is added on top.',
    'HELP_SHOP_CONFIG_CMSFOLDER' => 'Defines the available folders into which CMS pages can be organised in the administration area.',
    'HELP_SHOP_CONFIG_CNTOFNEWS' => 'Specifies how many news items are displayed in the news box in the shop.',
    'HELP_SHOP_CONFIG_CONFIRMAGB' => 'Customers are required to actively confirm the general terms and conditions during checkout.',
    'HELP_SHOP_CONFIG_CONFIRMCOOKIE' => 'Customers must actively consent to the use of cookies before they are set.',
    'HELP_SHOP_CONFIG_CSVSEPARATOR' => 'Defines the separator character used for CSV import and export.',
    'HELP_SHOP_CONFIG_DATEFORMAT' => 'Defines the date format displayed in the shop administration area.',
    'HELP_SHOP_CONFIG_DEBIT_OLD_BANK_INFORMATION_NOT_ALLOWED' => 'Only IBAN and BIC can be entered during the checkout. Bank account number and the bank code can only be entered if this check box is not activated.',
    'HELP_SHOP_CONFIG_DEFAULTVAT' => 'Sets the default VAT rate applied to all products that have no individual VAT rate assigned.',
    'HELP_SHOP_CONFIG_DELETERATINGLOGS' => 'If users rate a product, they cannot rate the product again. Here you can set after how many days users are allowed to rate a product again. Leave empty to disable - products can be rated only once per user.',
    'HELP_SHOP_CONFIG_DELIVERYCOSTS' => 'Shipping costs are calculated and displayed even when the customer is not yet logged in.',
    'HELP_SHOP_CONFIG_DISABLEARTDUBLICATES' => 'Copied products are not automatically set to active status.',
    'HELP_SHOP_CONFIG_DISABLEONLINEVATIDCHECK' => 'The online VAT ID check is executed if a customer from a foreign country inside the EU enters a VAT ID when ordering. If the VAT ID is valid, no VAT is calculated for this order.<br>If the check is disabled, the normal VAT for the according country is always calculated.',
    'HELP_SHOP_CONFIG_DOWNLOADS' => 'Shop with downloadable products. Activate here, that products can be ordered and downloaded.',
    'HELP_SHOP_CONFIG_DOWNLOADS_PATH' => 'Path where files of downloadable products are stored.',
    'HELP_SHOP_CONFIG_DOWNLOAD_EXPIRATION_TIME' => 'Specify the time in hours, the download link is valid after the first download. This is the default setting for all products.You can change this value for every file of product in Administer Products -> Products -> Downloads.',
    'HELP_SHOP_CONFIG_ENABLE_INTANGIBLE_PRODUCTS_AGREEMENT' => 'If this option is activated, users have to confirm terms and conditions for intangible or downloadable products in the fourth step of the check-out process. Please make sure this option is enabled for the specific item as well!',
    'HELP_SHOP_CONFIG_ENTERNETPRICE' => 'In admin area product prices must be entered as net prices.',
    'HELP_SHOP_CONFIG_EXCLUDENONMATERIALPRODUCTS' => 'Intangible products (e.g. gift certificates) are excluded from shipping cost calculation.',
    'HELP_SHOP_CONFIG_EXPORTNUMBEROFLINES' => 'Specifies how many lines are processed per tick during CSV export.',
    'HELP_SHOP_CONFIG_FIELDS_CONTACTFORM' => 'Here you can define the contact form fields a user necessarily has to fill.',
    'HELP_SHOP_CONFIG_INCLUDE_PRODUCT_REVIEW_LINKS_IN_ORDER_EMAIL' => 'Please double-check if this is legally compliant with the applicable laws. This setting will only be applied, if "user reviews and star ratings" is activated.',
    'HELP_SHOP_CONFIG_INLANDCUSTOMERS' => 'Customers from the selected countries are automatically assigned to the "Domestic Customers" user group.',
    'HELP_SHOP_CONFIG_INVITATION' => 'Invitation is used for inviting your friends to website and getting credit points for inviting.',
    'HELP_SHOP_CONFIG_LARGECUSTOMERPRICE' => 'Defines the minimum purchase value from which customers are assigned to the "Huge Turnover" user group.',
    'HELP_SHOP_CONFIG_LINK_EXPIRATION_TIME' => 'Specify the time in hours, the download link is valid after order. This is the default setting for all products.You can change this value for every file of product in Administer Products -> Products -> Downloads.',
    'HELP_SHOP_CONFIG_LINK_EXPIRATION_TIME_UNREGISTERED' => 'Here you can define how many times user can download from the same link, if user ordered without registration. This is the default setting for all products.You can change this value for every file of product in Administer Products -> Products -> Downloads.',
    'HELP_SHOP_CONFIG_LOADREVIEWS' => 'Users can review and rate your products with stars. If this setting is checked, the existing reviews/star ratings are loaded and shown with the product. This setting might degrade the performance of the shop.',
    'HELP_SHOP_CONFIG_MAX_DOWNLOADS_COUNT' => 'Here you can define how many times user can download from the same link after order. This is the default setting for all products.You can change this value for every file of product in Administer Products -> Products -> Downloads.',
    'HELP_SHOP_CONFIG_MIDLLECUSTOMERPRICE' => 'Defines the minimum purchase value from which customers are assigned to the "Medium Turnover" user group.',
    'HELP_SHOP_CONFIG_MINORDERPRICE' => 'Sets the minimum order value; orders below this amount are not accepted (leave empty to disable).',
    'HELP_SHOP_CONFIG_MUSTFILLFIELDS' => 'Here you can set the mandatory fields for user registration. Enter one field per row.<br>The most common entries are:<ul><li>oxuser__oxfname = First name</li><li>oxuser__oxlname = Last name</li><li>oxuser__oxstreet = Street</li><li>oxuser__oxstreetnr = House number</li><li>oxuser__oxzip = ZIP</li><li>oxuser__oxcity = City</li><li>oxuser__oxcountryid = Country</li><li>oxuser__oxfon = Telephone number</li></ul><br>You can also define the mandatory fields if users enter a different delivery address. The most common entries are:<ul><li>oxaddress__oxfname = First name</li><li>oxaddress__oxlname = Last name</li><li>oxaddress__oxstreet = Street</li><li>oxaddress__oxstreetnr = House number</li><li>oxaddress__oxzip = ZIP</li><li>oxaddress__oxcity = City</li><li>oxaddress__oxcountryid = Country</li><li>oxaddress__oxfon = Telephone number</li></ul>',
    'HELP_SHOP_CONFIG_NEWARTBYINSERT' => 'On the front page of your Shop the newest products are shown in <span class="filename_filepath_or_italic">Just arrived!</span>.  This setting determines how the newest products are calculated: by date of creation or by date of last change in admin/last order.',
    'HELP_SHOP_CONFIG_NROFCUSTOMERWHOARTICLES' => 'Specifies how many products are shown in the "Customers who bought this also bought" section.',
    'HELP_SHOP_CONFIG_NROFNEWCOMERARTICLES' => 'Specifies how many products are displayed in the "Just arrived!" (newest products) section.',
    'HELP_SHOP_CONFIG_NUMBEROFCROSSSELLARTICLES' => 'Specifies how many cross-selling products and accessories are shown on the product detail page.',
    'HELP_SHOP_CONFIG_NUMBEROFEMAILSPERTICK' => 'Specifies how many newsletter e-mails are sent by the system per tick.',
    'HELP_SHOP_CONFIG_NUMBEROFSIMILARARTICLES' => 'Specifies how many similar products are displayed on the product detail page.',
    'HELP_SHOP_CONFIG_ORDERFOLDER' => 'Defines the available folders into which orders can be organised in the order administration.',
    'HELP_SHOP_CONFIG_ORDEROPTINEMAIL' => 'If double-opt-in is active, users get an e-mail with a confirmation link when they register for the newsletter. Only if this confirmation link is used the user is registered for the newsletter.<br>Double-opt-in protects users from unwanted registrations. Without double-opt-in, any e-mail address can be registered for the newsletter. With double-opt-in, the owner of the e-mail address has to confirm the registration.',
    'HELP_SHOP_CONFIG_OVERRIDEZEROABCPRICES' => 'You can set up special prices for specific users: For each product you can enter A, B and C prices. If users are in the user group <span class="filename_filepath_or_italic">Price A</span>, the A price is shown to them instead of the normal price.<br>If this setting is checked, the normal product price is used if no A, B or C price is available.<br>You should activate this setting if you are using A, B and C prices: Otherwise 0,00 is displayed to the according users if no A, B or C price is set.',
    'HELP_SHOP_CONFIG_PARCELSERVICE' => 'Please fill in the tracking URL of your shipping provider. <i>##ID##</i> is a placeholder and will be replaced with the respective tracking number.',
    'HELP_SHOP_CONFIG_POINTSFORINVITATION' => 'The amount of credit points user gets who was invited by already registered user. Invited user must register to get these points. Aquired credit points are stored in user record and can be used by shop owner for any purpose.',
    'HELP_SHOP_CONFIG_POINTSFORREGISTRATION' => 'The amount of credit points user gets who invited somebody to shop. User gets credit points only if invited user registers into shop. Aquired credit points are stored in user record and can be used by shop owner for any purpose.',
    'HELP_SHOP_CONFIG_PSLOGIN' => 'Private Sales Login transforms regular shop into members only shop. This helps to develop customer communities with similar interests. This setting restricts access to all Shop pages.',
    'HELP_SHOP_CONFIG_RSSARTRECOMMLISTS' => 'Enables the RSS feed for the Listmania overview.',
    'HELP_SHOP_CONFIG_RSSBARGAIN' => 'Enables the RSS feed for bargain products.',
    'HELP_SHOP_CONFIG_RSSCATEGORIES' => 'Enables the RSS feed for categories.',
    'HELP_SHOP_CONFIG_RSSITEMSCOUNT' => 'Specifies how many entries are shown in the shop\'s RSS feeds.',
    'HELP_SHOP_CONFIG_RSSNEWEST' => 'Enables the RSS feed for the newest products.',
    'HELP_SHOP_CONFIG_RSSRECOMMLISTARTS' => 'Enables the RSS feed for products in Listmania lists.',
    'HELP_SHOP_CONFIG_RSSSEARCH' => 'Enables the RSS feed for search results.',
    'HELP_SHOP_CONFIG_RSSSELECTED' => 'Defines which RSS feeds are displayed and linked in the shop.',
    'HELP_SHOP_CONFIG_RSSTOPSHOP' => 'Enables the RSS feed for the top products of the shop.',
    'HELP_SHOP_CONFIG_SEARCHFIELDS' => 'Here you can define the database fields in which the product search searches. Enter one field per row.<br>The most common entries are:<ul><li>oxtitle = Title</li><li>oxshortdesc = Short description</li><li>oxsearchkeys = Search terms entered for each product</li><li>oxartnum = Product number</li></ul>',
    'HELP_SHOP_CONFIG_SETORDELETECURRENCY' => 'Add or remove currencies. Each line contains currency parameters separated by the symbol @.<br /><br /><ul><li>currency code according to ISO 4217 (e.g. EUR)</li><li>currency rate to basic currency with the value 1.00</li><li>decimal separator</li><li>thousands separator</li><li>currency sign</li><li>number of decimal places</li><li>optional parameter "Front". If entered, the currency sign shows up in front of the price.</li></ul>',
    'HELP_SHOP_CONFIG_SHIPPINGCOUNTRYVAT' => 'The shipping country is used for VAT calculation instead of the customer\'s billing country.',
    'HELP_SHOP_CONFIG_SHOWORDERBUTTONONTHETOP' => 'An additional "Order now" button is shown at the top of the page in the fourth checkout step.',
    'HELP_SHOP_CONFIG_SHOWTSCODMESSAGE' => 'In the 4th step of the checkout process the CMS page "oxtscodmessage" is additionally displayed.',
    'HELP_SHOP_CONFIG_SHOWTSINTERNATIONALFEESMESSAGE' => 'In the 4th step of the checkout process the CMS page "oxtsinternationalfees" is additionally displayed.',
    'HELP_SHOP_CONFIG_SORTFIELDS' => 'Here you can define the database fields which can be used for sorting product lists. Enter one field per row.<br>The most common entries are:<ul><li>oxtitle = Title</li><li>oxprice = Price</li><li>oxvarminprice = The lowest price if variants with different prices are used.</li><li>oxartnum = Product numbers</li><li>oxrating = Rating of the products</li><li>oxstock = Stock</li></ul>',
    'HELP_SHOP_CONFIG_SORTITEMSLIST' => 'Customers can sort product lists in the shop by various criteria.',
    'HELP_SHOP_CONFIG_STOCKOFFDEFAULTMESSAGE' => 'For each product you can set up a message if the product is not in stock.<br>If this setting is active, a message is shown if no specific message for for a product is entered. The default message <span class="filename_filepath_or_italic">This item is not in stock and must be back-ordered</span> is shown.',
    'HELP_SHOP_CONFIG_STOCKONDEFAULTMESSAGE' => 'For each product you can set up a message if the product is on stock.<br>If this setting is active, a message is shown if no specific message for for a product is entered. The default message <span class="filename_filepath_or_italic">Ready for shipping</span> is shown.',
    'HELP_SHOP_CONFIG_STOCKWARNINGLIMIT' => 'Sets the stock level at which customers are notified that only a few items remain in stock.',
    'HELP_SHOP_CONFIG_TIMEFORMAT' => 'Defines the time format displayed in the shop administration area.',
    'HELP_SHOP_CONFIG_USENEGATIVESTOCK' => 'With <span class="navipath_or_inputname">Allow negative Stock Values</span> you can define how stock levels are calculated of products are out of stock:<br><ul><li>If the setting is checked, negative stock values are calculated if further units are bought.</li><li>If the setting is unchecked, the stock value never falls below 0, even if further units are bought.</li></ul>',
    'HELP_SHOP_CONFIG_USESTOCK' => 'Enables stock management so that inventory levels are tracked and orders are restricted accordingly.',
    'HELP_SHOP_CONFIG_VIEWNETPRICE' => 'In frontend product prices are shown as net prices.',
    'HELP_SHOP_CONFIG_WARNONSAMEARTNUMS' => 'Displays a warning when a product number is already used by another product.',
    'HELP_SHOP_MAIN_ACTIVE' => 'With <span class="navipath_or_inputname">Active</span> you can enable/disable the complete Shop. If the Shop is disabled, a message saying the Shop is temporary offline is displayed to the users. This can be useful for maintenance.',
    'HELP_SHOP_MAIN_BANKCODE' => 'Bank code',
    'HELP_SHOP_MAIN_BANKNAME' => 'The bank name',
    'HELP_SHOP_MAIN_BANKNUMBER' => 'Account number of the owning company',
    'HELP_SHOP_MAIN_BICCODE' => 'BIC/SWIFT number of the bank.',
    'HELP_SHOP_MAIN_COMPANY' => 'The owner company of this shop.',
    'HELP_SHOP_MAIN_COURT' => 'District court where the company is registered',
    'HELP_SHOP_MAIN_FORGOTPWDSUBJECT' => 'Email subject for the "Forgot password" email.',
    'HELP_SHOP_MAIN_HRBNR' => 'Commercial register number',
    'HELP_SHOP_MAIN_IBANNUMBER' => 'IBAN',
    'HELP_SHOP_MAIN_INFOEMAIL' => 'All e-mails sent via the contact page are sent to this e-mail address.',
    'HELP_SHOP_MAIN_NOWSENDEDSUBJECT' => 'Email subject for shipping confirmations.',
    'HELP_SHOP_MAIN_ORDEREMAIL' => 'When users order they receive an e-mail with a summary of the order. Answers to this e-mail are sent to <span class="navipath_or_inputname">Order e-mail reply</span>.',
    'HELP_SHOP_MAIN_ORDERSUBJECT' => 'Email subject for the order confirmation email.',
    'HELP_SHOP_MAIN_OWNEREMAIL' => 'When users order, you receive an e-mail with a summary of the order. These e-mails are sent to <span class="navipath_or_inputname">Order e-mails to</span>.',
    'HELP_SHOP_MAIN_PRODUCTIVE' => 'Non-productive Shop mode is intended for Shop installation, configuration, template customization and module debugging phase. As soon as productive mode is turned <span class="warning_or_important_hint">ON</span>, the cache handling and the error reporting behavior is optimized for the live shop.<br><span class="warning_or_important_hint">Activate this setting when the Shop is launched.</span>',
    'HELP_SHOP_MAIN_REGISTERSUBJECT' => 'Email subject for new registrations.',
    'HELP_SHOP_MAIN_SHOPNAME' => 'The name of this shop',
    'HELP_SHOP_MAIN_SMTPPASSWORD' => 'The password for logging into the mail server.',
    'HELP_SHOP_MAIN_SMTPSERVER' => 'SMTP data is needed for sending e-mails (e.g. sending customers an order confirmation e-mail).',
    'HELP_SHOP_MAIN_SMTPUSER' => 'Mail user used for logging into the mail server. Important for spam protection.',
    'HELP_SHOP_MAIN_TAXNUMBER' => 'Tax number',
    'HELP_SHOP_MAIN_VATNUMBER' => 'European VAT identification number.',
    'HELP_SHOP_MALL_MALLMODE' => 'Here you can set what is shown as front page of this Shop:<ul><li><span class="navipath_or_inputname">Show shop selector</span>: A page where the different eShops can be selected is shown.</li><li><span class="navipath_or_inputname">Show main shop front page</span>: The normal front page of this Shop is shown.</li></ul>',
    'HELP_SHOP_MALL_PRICEADDITION' => 'You can define a surcharge on all product prices in this shop: Enter the surcharge and select if its a percental (<span class="userinput_or_code">%</span>) or absolute (<span class="userinput_or_code">abs</span>).',
    'HELP_SHOP_PERF_CALCVATONLYFORBASKETORDER' => 'Controls whether country-specific VAT rates are calculated only in the shopping cart and checkout (improves performance outside the checkout).',
    'HELP_SHOP_PERF_CHECKIFTPLCOMPILE' => 'If this setting is activated the Shop checks on each call if any templates were changed. If so, the output is recalculated. Activate this setting when adapting templates, deactivate it if the Shop is live for better performance.',
    'HELP_SHOP_PERF_CLEARCACHEONLOGOUT' => 'Usually the complete cache is emptied as soon as you save any changes in the Shop admin. This can lead to performance problems in admin. If this setting is activated, the cache is only emptied when you log out from Shop admin.',
    'HELP_SHOP_PERF_DISBASKETSAVING' => 'The shopping cart of registered users is saved. When they visit your Shop again, the shopping cart contents are loaded. If you activate this setting, the shopping carts aren\'t saved any more.',
    'HELP_SHOP_PERF_DONTSHOWEMTYCATEGORIES' => 'Controls whether empty categories (without sub-categories and without products) are hidden in the shop frontend.',
    'HELP_SHOP_PERF_LOADACCESSOIRES' => 'Controls whether accessory products are loaded on the product detail page in the shop frontend (affects performance).',
    'HELP_SHOP_PERF_LOADACTION' => 'If this setting is checked, promotions like <span class="filename_filepath_or_italic">Just arrived!</span> and <span class="filename_filepath_or_italic">Top of the Shop</span> are loaded and shown.',
    'HELP_SHOP_PERF_LOADCROSSSELLING' => 'Controls whether cross-selling products are loaded on the product detail page in the shop frontend (affects performance).',
    'HELP_SHOP_PERF_LOADCURRENCY' => 'Controls whether the currency selector is displayed in the shop frontend (affects performance).',
    'HELP_SHOP_PERF_LOADCUSTOMERWHOBOUGHTTHIS' => 'Controls whether the "Customers who bought this product also purchased ..." section is loaded in the shop frontend (affects performance).',
    'HELP_SHOP_PERF_LOADDELIVERY' => 'If you deactivate this setting, no shipping costs are calculated: The shipping costs are always 0.00 EUR.',
    'HELP_SHOP_PERF_LOADFULLTREE' => 'If this setting is checked, the complete category tree is shown in the category navigation (all categories are expanded). This only works if the category navigation is not shown at top.',
    'HELP_SHOP_PERF_LOADLANGUAGES' => 'Controls whether the language selector is displayed in the shop frontend (affects performance).',
    'HELP_SHOP_PERF_LOADMANUFACTURERTREE' => 'Controls whether the manufacturer list is loaded and displayed in the shop frontend (affects performance).',
    'HELP_SHOP_PERF_LOADNEWS' => 'Controls whether news items are loaded in the shop frontend (affects performance).',
    'HELP_SHOP_PERF_LOADNEWSONLYSTART' => 'Controls whether news items are loaded only on the start page (reduces performance impact on all other pages).',
    'HELP_SHOP_PERF_LOADPRICE' => 'If you deactivate this setting, no product prices are calculated: No prices are shown.',
    'HELP_SHOP_PERF_LOADPRICEFORADDLIST' => 'Controls whether prices are shown in the "Top of the Shop" and "Just arrived!" sections (affects performance).',
    'HELP_SHOP_PERF_LOADSELECTLIST' => 'Controls whether selection lists are loaded on the product detail page in the shop frontend (affects performance).',
    'HELP_SHOP_PERF_LOADSELECTLISTSINALIST' => 'Normally selection lists are only shown in the detail view of a product. If you activate this setting, the selection lists are also shown in product lists (e. g. search results, categories).',
    'HELP_SHOP_PERF_LOADSIMILAR' => 'Controls whether similar products are loaded on the product detail page in the shop frontend (affects performance).',
    'HELP_SHOP_PERF_LOADVARIANTS' => 'Controls whether variants are loaded in product lists such as search results and category views (high memory usage, may affect performance on low-resource servers).',
    'HELP_SHOP_PERF_NEWESTARTICLES' => 'A list of newest products are shown in <span class="filename_filepath_or_italic">Just arrived!</span>. Here you can set how the list is generated:<ul><li><span class="userinput_or_code">inactive</span>: The list is not shown.</li><li><span class="userinput_or_code">manual</span>: You can define the products in <span class="navipath_or_inputname">Customer Info -> Promotions -></span> in the promotion <span class="filename_filepath_or_italic">Just arrived!</span>.</li><li><span class="userinput_or_code">automatic</span>: The products are calculated automatically.</li></ul>',
    'HELP_SHOP_PERF_PARSELONGDESCINSMARTY' => 'If this setting is active, the descriptions of products and categories are parsed trough Smarty: You can use Smarty tags (e. g. for using variables) <br>',
    'HELP_SHOP_PERF_SEO_CACHE' => 'Enabled SEO cache increases performance, but requires a lot of disk space in /tmp directory.',
    'HELP_SHOP_PERF_SHOWACTCATARTCOUNT' => 'Controls whether the number of contained products is displayed next to category names in the navigation (affects performance).',
    'HELP_SHOP_PERF_SYSREQ_CHECK' => 'Runs the system health check when accessing the admin home page and displays messages if necessary. In special configurations this may affect the performance of the admin panel.',
    'HELP_SHOP_PERF_TOPSELLER' => 'A list of most often sold products is shown in <span class="filename_filepath_or_italic">Top of the Shop</span>. Here you can set how the list is generated:<ul><li><span class="userinput_or_code">inactive</span>: The list is not shown.</li><li><span class="userinput_or_code">manual</span>: You can define the products in <span class="navipath_or_inputname">Customer Info -> Promotions -></span> in the promotion <span class="filename_filepath_or_italic">Top of the Shop</span>.</li><li><span class="userinput_or_code">automatic</span>: The products are calculated automatically.</li></ul>',
    'HELP_SHOP_PERF_USESELECTLISTPRICE' => 'In selection lists surcharges/discounts can be set up. If this setting is checked, the surcharges/discounts are loaded and applied. If unchecked, the surcharges/discounts aren\'t applied.',
    'HELP_SHOP_PERF_USETIMECHECKINARTLOAD' => 'Controls whether the "Active from" and "Active until" dates are checked when loading products (affects performance).',
    'HELP_SHOP_RDFA_COND' => 'Select here, what term describes the condition of the products (new, used or refurbished).',
    'HELP_SHOP_RDFA_CONTENT_DELIVERY' => 'Select here, in which content page not to RDFa assigned shipping information is displayed, e.g. "Shipping and charges". To assign your shipping methods to RDFa payment methods in general go to: Shop Settings -> Shipping Methods -> RDFa.',
    'HELP_SHOP_RDFA_CONTENT_OFFERER' => 'Select here, in which content page Shop main information is displayed, e.g. "About Us".',
    'HELP_SHOP_RDFA_CONTENT_PAYMENT' => 'Select here, in which content page not to RDFa assigned payment information is displayed, e.g. "Terms and Conditions". To assign your payment methods to RDFa payment methods in general go to: Shop Settings -> Payment Methods -> RDFa.',
    'HELP_SHOP_RDFA_COSTUMER' => 'The types of customers for which shop products are valid (End user, Reseller, Business and/or Public).',
    'HELP_SHOP_RDFA_DUNS' => 'The Dun & Bradstreet D-U-N-S is a nine-digit number used to identify legal entities.',
    'HELP_SHOP_RDFA_DURATION_OFFERINGS' => 'This property specifies the time of the validity of the products, e.g. 1 day, 1 week or 1 month.',
    'HELP_SHOP_RDFA_DURATION_PRICES' => 'Specify here the time of the validity of the costs of products, payment and shipping (e.g. 1 day, 1 week).',
    'HELP_SHOP_RDFA_EMBEDDING' => 'Controls whether structured RDFa data is automatically embedded into shop pages to provide machine-readable product information.',
    'HELP_SHOP_RDFA_FNC' => 'Select the business function of the products here. For example, are they offered to sell, to lease or to repair?',
    'HELP_SHOP_RDFA_GEO_LATITUDE' => 'The latitude of the store as part of geo position. Please enter numbers only.',
    'HELP_SHOP_RDFA_GEO_LONGITUDE' => 'The longitude of the store as part of geo position. Please enter numbers only.',
    'HELP_SHOP_RDFA_GLN' => 'Global Location Number (GLN) for the company. The Global Location Number is a thirteen-digit number used to identify parties and physical locations.',
    'HELP_SHOP_RDFA_ISIC' => 'The International Standard of Industrial Classification of All Economic Activities (ISIC) code for your company. See http://unstats.un.org/unsd/cr/registry/isic-4.asp.',
    'HELP_SHOP_RDFA_LOGO_URL' => 'The Web address (URL) of a logo or image.',
    'HELP_SHOP_RDFA_NAICS' => 'North American Industry Classification System (NAICS) code for your company. See http://www.census.gov/eos/www/naics/.',
    'HELP_SHOP_RDFA_RATING_MAX' => 'Possible maximum value refer to the scale used for ratings in your shop. This value is not the highest current rating of a product!',
    'HELP_SHOP_RDFA_RATING_MIN' => 'Possible minimum value refer to the scale used for ratings in your shop. This value is not the lowest current rating of a product!',
    'HELP_SHOP_RDFA_SHOW_PRODUCTSTOCK' => 'If this option is on means, that the real product stock is shown.',
    'HELP_SHOP_RDFA_VAT' => 'This option specifies whether the tax (VAT) is included in the price and delivery/payment costs or not.',
    'HELP_SHOP_SEO_IDSSEPARATOR' => 'The separator is used if category names and product names consist of several words. The separator is used instead of spaces, e.g. www.youreshop.com/category-name-of-several-words<br>If no separator is entered, - is used.',
    'HELP_SHOP_SEO_LOWERCASEURLS' => 'Lowercase all upper case characters in SEO urls. E.g. www.youreshop.com/Kiteboarding/Kites/ transforms to www.youreshop.com/kiteboarding/kites/.',
    'HELP_SHOP_SEO_RESERVEDWORDS' => 'Some URLs are defined in O3-Shop, like www.youreshop.com/admin for accessing shop admin. If a category was named <span class="filename_filepath_or_italic">admin</span> the SEO URL would be www.youreshop.com/admin too - the category couldn\'t be accessed. Therefore the SEO suffix is attached to these URLs. You can define here which URLs are suffixed automatically.',
    'HELP_SHOP_SEO_SAFESEOPREF' => 'If several products have the same name and are in the same category, they would get the same SEO URL. For avoiding this, the SEO Suffix is attached. If no SEO Suffix is defined, <span class="filename_filepath_or_italic">o3</span> is used.',
    'HELP_SHOP_SEO_SKIPTAGS' => 'If no META tags are defined for products and categories, the META tags are created automatically. thereby very common words can be omitted. All words entered here are omitted when creating the META tags.',
    'HELP_SHOP_SEO_STARTTITLE' => 'Sets the page title of the shop front page as displayed in the browser tab and search engine results.',
    'HELP_SHOP_SEO_STATICURLS' => 'For special pages (e. g. general terms and conditions) you can enter fixed SEO URLs. When selecting a static URL, the normal URL is shown in <span class="navipath_or_inputname">Standard URL</span>. In the input fields below you can define a SEO URL for each language.',
    'HELP_SHOP_SEO_STDURL' => 'Sets the standard URL of the shop, which is used as the base for generating all other URLs.',
    'HELP_SHOP_SEO_TITLEPREFIX' => 'Each page has a title. this title is shown in the top bar of the browser window. With <span class="navipath_or_inputname">Title Prefix</span> and <span class="navipath_or_inputname">Title Suffix</span> you can fill in text before and after page titles:<br><ul><li>In <span class="navipath_or_inputname">Title Prefix</span>, enter the text to be displayed in front of the title.</li></ul>',
    'HELP_SHOP_SEO_TITLESUFFIX' => 'Each page has a title. this title is shown in the top bar of the browser window. With <span class="navipath_or_inputname">Title Prefix</span> and <span class="navipath_or_inputname">Title Suffix</span> you can fill in text before and after page titles:<br><ul><li>In <span class="navipath_or_inputname">Title Suffix</span> enter the text to be displayed behind the title.</li></ul>',
    'HELP_SHOP_SYSTEM_ATTRIBUTESPERCENT' => 'Sets the percentage of matching attributes required for two products to be classified as similar.',
    'HELP_SHOP_SYSTEM_DEFAULTIMAGEQUALITY' => 'Recommended settings are from 40-80:<br><ul><li>Under 40, the compression gets clearly visible and the pictures are blurred.</li><li>Above 80 hardly any quality improvement can be detected, but the filesize increases enormously.</li></ul><br>The default value is 75.',
    'HELP_SHOP_SYSTEM_DISABLENAVBARS' => 'If this setting is checked, most navigation elements aren\'t shown during checkout. Thereby users aren\'t distracted unnecessarily during checkout.',
    'HELP_SHOP_SYSTEM_GBMODERATE' => 'Controls whether product reviews must be approved by an administrator before they are published.',
    'HELP_SHOP_SYSTEM_INLINEIMGEMAIL' => 'If the setting is checked, the pictures in e-mails are sent together with the e-mail. If the setting is unchecked, the pictures are downloaded by the e-mail program when the e-mail is opened.',
    'HELP_SHOP_SYSTEM_INTERFACEPROFILES' => 'Sets the profiles for the administration area (screen resolution and number of rows in the list section).',
    'HELP_SHOP_SYSTEM_ISERVERTIMESHIFT' => 'The server the Shop is running on can be in a different time zone. With this setting the time shift can be adjusted: Enter the amount of hours that are to be added/subtracted from the server time, e. g. <kdb>+2</kdb> or <kdb>-2</kdb>',
    'HELP_SHOP_SYSTEM_LDAP' => 'Please edit file Core/oxldap.php.',
    'HELP_SHOP_SYSTEM_LOGSKIPTAGS' => 'Defines which changes in the administration area are excluded from the admin activity log.',
    'HELP_SHOP_SYSTEM_ORDERDISNOREG' => 'Controls whether customers are required to register before they can place an order.',
    'HELP_SHOP_SYSTEM_OTHERCOUNTRYORDER' => 'Here you can set if orders can be made in countries for which no shipping costs are defined:<ul><li>If the setting is checked, users can order: The users are notified that they are informed about the shipping costs manually.</li><li>If the setting is unchecked, users from countries for which no shipping costs are defined cannot order.</li></ul>',
    'HELP_SHOP_SYSTEM_SHOWREMEMBERME' => 'Controls whether the "Remember me" option is displayed in the shop login box.',
    'HELP_SHOP_SYSTEM_SHOWVARIANTREVIEWS' => 'This setting affects how reviews for variants are handled: If the setting is checked, remarks from variants are also shown at the parent product.',
    'HELP_SHOP_SYSTEM_STOREIPS' => 'Controls whether user IP addresses are stored (please verify compliance with applicable data protection regulations).',
    'HELP_SHOP_SYSTEM_USEMULTIDIMENSIONVARIANTS' => 'Controls whether multidimensional variants (e.g., size and colour simultaneously) are enabled in the shop.',
    'HELP_SHOP_SYSTEM_UTILMODULE' => 'Please enter your custom PHP file here, which will overwrite Shop functions at shop start.',
    'HELP_SHOP_SYSTEM_VARIANTINHERITAMOUNTPRICE' => 'Here you can set whether scales prices are inherited from the parent product: If the setting is checked, the scale prices of the parent product are also used for its variants.',
    'HELP_SHOP_SYSTEM_VARIANTPARENTBUYABLE' => 'This setting affects if parent products can be bought:<ul><li>If the setting is checked, the parent products can be bought, too.</li><li>If the setting is unchecked, only variants of the parent product can be bought.</li></ul>',
    'HELP_SHOP_SYSTEM_VARIANTSSELECTION' => 'In Shop there are many lists for assigning products, e.g. assigning products to discounts. If this setting is checked, variants are shown in these lists, too.',
    'HELP_TOOLS_MAIN_SQLDUMB' => 'Import an SQL file to execute database commands directly (large files should be uploaded via FTP).',
    'HELP_TOOLS_MAIN_UPDATESQL' => 'Run an SQL update script to update the database structure or its contents.',
    'HELP_USER_ADDRESS_DELIVERYADDRESS' => 'Known delivery addresses.',
    'HELP_USER_EXTEND_BONI' => 'Here you can enter a numerical value for the credit rating of the user. With the credit rating you can influence which payment methods are available to this user.',
    'HELP_USER_EXTEND_EMAILFAILED' => 'If no e-mails can be sent to the e-mail address of this user, check this setting. Then no newsletters are sent to this user any more. Other e-mails are still sent.',
    'HELP_USER_EXTEND_MOBILFON' => 'The mobile phone number',
    'HELP_USER_EXTEND_NEWSLETTER' => 'This setting shows if the user subscribed to the newsletter.',
    'HELP_USER_EXTEND_PRIVATFON' => 'The private phone number',
    'HELP_USER_MAIN_CUSTOMERSNR' => 'The customer number of this user.',
    'HELP_USER_MAIN_EMAILLOGIN' => 'The email address the user logs in with.',
    'HELP_USER_MAIN_HASPASSWORD' => 'Here you can distinguish if users registered when ordering:<ul><li>If a password is set, the user registered.</li><li>If no password is set, the user ordered without registering.</li></ul>',
    'HELP_USER_MAIN_NAME' => 'The first and last name of the user.',
    'HELP_USER_MAIN_NEWPASSWORD' => 'A new password for this user (leave blank to keep the existing one).',
    'HELP_USER_MAIN_RIGHTS' => 'The access rights of this user in the admin area.',
    'HELP_USER_MAIN_STRNR' => 'The street and house number of the user.',
    'HELP_USER_PAYMENT_METHODS' => 'On this tab you can:<ul><li>Browse and manage existing user payment methods.<li>Create new payment methods and set default values, for example direct debit.</li></ul>',
    'HELP_USER_PAYMENT_PAYMENTTYPE' => 'The payment methods.',
    'HELP_VENDOR_MAIN_ICONUPLOAD' => 'Upload an icon image for this vendor that will be displayed in the shop.',
    'HELP_VOUCHERSERIE_MAIN_ALLOWOTHERSERIES' => 'Here you can set if users are allowed to use coupons together with coupons of other coupon series in a single order.',
    'HELP_VOUCHERSERIE_MAIN_ALLOWSAMESERIES' => 'Here you can set whether users are allowed to use several coupons of this coupon series in a single order.',
    'HELP_VOUCHERSERIE_MAIN_CALCULATEONCE' => 'If you assign products or categories to your coupon, deactivate this option to calculate this coupon to each product per cart position. Activate if the coupon shall be valid only once per cart position.',
    'HELP_VOUCHERSERIE_MAIN_DISCOUNT' => 'In <span class="navipath_or_inputname">Discount</span>, you specify the magnitude of the discount. You can use the selection list after the entry field to specify whether the discount is to be applied as an absolute discount or as a percentage discount:<ul><li><span class="userinput_or_code">abs</span>: The discount is an absolute discount, e.g. EUR 5.</li><li><span class="userinput_or_code">%</span>: The discount is a percentage discount, e.g. 10 percent of the purchase price.</li></ul>',
    'HELP_VOUCHERSERIE_MAIN_MINORDERPRICE' => 'Minimum order value for which a voucher from this series is valid',
    'HELP_VOUCHERSERIE_MAIN_RANDOMNUM' => 'If this setting is active a random number is calculated for each coupon.',
    'HELP_VOUCHERSERIE_MAIN_SAMESEROTHERORDER' => 'Here you can set if users can use coupons of this coupon series in multiple orders.',
    'HELP_VOUCHERSERIE_MAIN_VOUCHERNUM' => 'Here you can enter a coupon number. This number is used when creating new coupons if <span class="navipath_or_inputname">Random Numbers</span> is deactivated. All Coupons get the same coupon numberon.',
    'HELP_WRAPPING_MAIN_PICTURE' => 'With <span class="navipath_or_inputname">Picture</span> and <span class="navipath_or_inputname">Upload Picture</span> you can upload a picture for the gift wrapping. In <span class="navipath_or_inputname">Upload Picture</span>, select the picture to upload. When clicking on <span class="navipath_or_inputname">Save</span>, the picture is uploaded. After uploading, the filename is shown in <span class="navipath_or_inputname">Picture</span>.',
    'HELP_WRAPPING_MAIN_PICUPLOAD' => 'Upload a preview image for this wrapping option that will be shown to the customer during checkout.',
];
