services:
  _defaults:
    autowire: true
    public: false
  OxidEsales\EshopCommunity\Internal\Framework\DIContainer\Dao\ProjectYamlDaoInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\DIContainer\Dao\ContainerAwareProjectYamlDao
    arguments:
      Symfony\Component\Filesystem\Filesystem: '@oxid_esales.symfony.file_system'
      $context: '@OxidEsales\EshopCommunity\Internal\Transition\Utility\BasicContextInterface'
