services:
  db:
    image: mysql:8.0
    container_name: o3shop-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${O3SHOP_CONF_DBROOT}
      MYSQL_DATABASE: ${O3SHOP_CONF_DBNAME}
      MYSQL_USER: ${O3SHOP_CONF_DBUSER}
      MYSQL_PASSWORD: ${O3SHOP_CONF_DBPWD}
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  shop:
    build:
      dockerfile: Dockerfile
    container_name: o3shop-app
    depends_on:
      - db
    volumes:
      - ./../:/var/www/html
    environment:
      PATH: /var/www/html/vendor/o3-shop/testing-library/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      TZ: Europe/Berlin
    ports:
      - "8080:80"
    working_dir: /var/www/html
    healthcheck:
      test: [ "CMD", "test", "!", "-f", "/tmp/o3setup-running" ]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 5s

  mailpit:
    image: axllent/mailpit
    container_name: o3shop-mailpit
    restart: unless-stopped
    volumes:
      - ./mailpit/data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  adminer:
    image: adminer:latest
    container_name: o3shop-adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      MYSQL_ROOT_PASSWORD: ${O3SHOP_CONF_DBROOT}
      MYSQL_DATABASE: ${O3SHOP_CONF_DBNAME}
      MYSQL_USER: ${O3SHOP_CONF_DBUSER}
      MYSQL_PASSWORD: ${O3SHOP_CONF_DBPWD}



