version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: o3shop-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"

  shop:
    build:
      dockerfile: Dockerfile
    container_name: o3shop-app
    depends_on:
      - db
    volumes:
      - ./../:/var/www/html
    environment:
      PATH: /var/www/html/vendor/o3-shop/testing-library/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
      - "8090:80"
    working_dir: /var/www/html

