name: 'shop-ce'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app
    ports:
      - "8080:80"
    volumes:
      - ./..:/var/www/html
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://o3shop:o3shop@db/o3shop
      TZ: Europe/Berlin
      PATH: /var/www/html/vendor/o3-shop/testing-library/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: o3shop
      MYSQL_USER: o3shop
      MYSQL_PASSWORD: o3shop
    volumes:
      - db_data:/var/lib/mysql
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  db_data:
