<?php

namespace OxidEsales\EshopCommunity\Application\Model;

use Doctrine\DBAL\Query\QueryBuilder;
use OxidEsales\Eshop\Core\Exception\UserException;
use OxidEsales\Eshop\Core\Model\BaseModel;
use OxidEsales\Eshop\Core\Registry;
use OxidEsales\EshopCommunity\Internal\Container\ContainerFactory;
use OxidEsales\EshopCommunity\Internal\Framework\Database\QueryBuilderFactoryInterface;

class RightsRoles extends BaseModel
{
    public $_sCoreTable = 'o3rightsroles';

    public function __construct()
    {
        parent::__construct();

        $this->init($this->_sCoreTable);
    }
//
//    public function clearItemsFromUser(string $userId)
//    {
//        /** @var QueryBuilder $queryBuilder */
//        $queryBuilder = ContainerFactory::getInstance()
//            ->getContainer()
//            ->get(QueryBuilderFactoryInterface::class)
//            ->create();
//
//        $queryBuilder->delete($this->getCoreTableName())
//            ->where(
//                $queryBuilder->expr()->and(
//                    $queryBuilder->expr()->eq(
//                        'userid',
//                        $queryBuilder->createNamedParameter($userId)
//                    ),
//                    $queryBuilder->expr()->eq(
//                        'shopid',
//                        $queryBuilder->createNamedParameter(Registry::getConfig()->getShopId())
//                    )
//                )
//            );
//
//        $queryBuilder->execute();
//    }
//
//    public function saveItemForUser(string $navigationId, string $userId)
//    {
//        $this->assign([
//            'userid'        => $userId,
//            'shopid'        => Registry::getConfig()->getShopId(),
//            'navigationid'  => $navigationId
//        ]);
//
//        return $this->save();
//    }
//
//    public function save()
//    {
//        if ($this->getFieldData('userid') === $this->getUser()->getId()) {
//            throw oxNew(UserException::class, 'admin rights restrictions are not allowed for current user');
//        }
//
//        // at least one admin user have rights to see admin rights
//
//        return parent::save(); // TODO: Change the autogenerated stub
//    }
}