<?php

/**
 * This file is part of O3-Shop.
 *
 * O3-Shop is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * O3-Shop is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with O3-Shop.  If not, see <http://www.gnu.org/licenses/>
 *
 * @copyright  Copyright (c) 2026 O3-Shop (https://www.o3-shop.com)
 * @license    https://www.gnu.org/licenses/gpl-3.0  GNU General Public License 3 (GPLv3)
 */

declare(strict_types=1);

namespace OxidEsales\EshopCommunity\Internal\ReleaseTooling\Notes;

/**
 * Source of per-repo release notes between two tags. Reference impl
 * delegates to GitHub's `releases/generate-notes` API; tests inject
 * a fake.
 */
interface ReleaseNotesProvider
{
    /**
     * Fetches release-notes markdown for a repo, generated by GitHub
     * for the tag range (previous, new].
     *
     * @return string markdown body. May be empty when no PRs landed
     *     between the tags. The provider SHOULD NOT throw on
     *     transport-level failures — return a stub markdown describing
     *     the failure so the aggregated body still ships.
     */
    public function notesFor(string $package, string $previousTag, string $newTag): string;
}
